[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

# Change the `name` of this constraint to be the import path of the upstream 
# Terraform provider, and set the `version` to be the tag name of the release
# you wish to pin to.
#
# If it is necessary to fork the provider, set the `name` to the canonical import
# path (i.e. github.com/terraform-providers/terraform-provider-x), and set the
# `source` to the fork address. Then set the `branch` to `pulumi-master` in the
# fork, and ensure `version` is not set.
[[constraint]]
  version = "v1.0.0"
  name = "github.com/terraform-providers/terraform-provider-x"

  [constraint.metadata]
    govendor-override = true
    govendor-exclude-prefixes = [
      "github.com/golang/protobuf",
    ]

